name: Trigger auto deployment for a001

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/a001-AutoDeployTrigger-790470ff-f87c-4f20-b878-3e8e94348fe1.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/
          username: ${{ secrets.A001_REGISTRY_USERNAME }}
          password: ${{ secrets.A001_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: https://index.docker.io//tumbaljos/cs2:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.A001_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n a001 -g josgandos01 --server https://index.docker.io/ --username  ${{ secrets.A001_REGISTRY_USERNAME }} --password ${{ secrets.A001_REGISTRY_PASSWORD }}
            az containerapp update -n a001 -g josgandos01 --image https://index.docker.io//tumbaljos/cs2:${{ github.sha }}
